apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-3xwx
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0060-tenant/tkrw-pr712-0075-0060-app/devfile-sample-3xwx@sha256:e5726d92737e9b6adb21c73d6454137d4526c9adbbbb6209f8c86179902a5532
        name: my-nodejs
        resources: {}
status: {}
